apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dbuser.notepass.de
spec:
  group: notepass.de
  names:
    kind: DbUser
    plural: dbuser
    shortNames:
      - dbu
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                request:
                  type: object
                created:
                  type: string