apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dbusers.notepass.de
spec:
  group: notepass.de
  names:
    kind: DbUser
    plural: dbusers
    shortNames:
      - dbu
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                db_type:
                  type: string
                custom_db_name_prop:
                  type: string
                postgres:
                  type: object
                  properties:
                    extensions:
                      type: array
                      items:
                        type: string
